Svg
StanislavMironenko/Music pull request #2
Opened 2022-06-10 16:55 UTC by Oleksandr-Alex-02

добавив фотку , плеер пока все)

2022-06-10 20:30 UTC, StanislavMironenko approved these changes

2022-06-10 20:44 UTC, StanislavMironenko approved these changes

2022-06-11 07:51 UTC, Oleksandr-Alex-02 reviewed
все ок там просто претІре форматнув код тай все

2022-06-11 09:07 UTC, StanislavMironenko approved these changes

2022-06-11 09:08 UTC, StanislavMironenko approved these changes

2022-06-11 15:58 UTC, StanislavMironenko requested changes
фывфывфы

2022-06-11 16:06 UTC, closed without merging